### ISSUE TITLE
Golden Rectangle not working

### ISSUE THREAD

**Issue by myurtsev** [ichord/sketch-divine-proportions#2]
Hi!
First of all; thank you for this awesome plugin! I love using it but i've just encountered a problem. 
I think this is because of the new update of Sketch (3.4.2) but the golden rectangle option is not working anymore. The other options are working perfectly.

Thanks!

**Comment by ichord** [comment]
Glad to know you love it :smile: 
I will try to fix it on the weekend.

**Comment by ichord** [comment]
@myurtsev fixed.
