### ISSUE TITLE
Is it can't work in Sketch v3.6.1

### ISSUE THREAD

**Issue by ilklatte** [ichord/sketch-divine-proportions#3]
I'm looking for a plugin could help to draw golden ratio line quickly. I found this plugin.  I do things according installing of README.md. And then select `Golden Rectangle` in the `Plugin` menu, nothing happened in Sketch.
Is something i missed, or it can't work in Sketch version 3.6.1?
Thanks for your helping!

**Comment by ichord** [comment]
May be the Sketch API was changed. I will try to fix it on weekend.

**Comment by ilklatte** [comment]
Thanks very much!
