### ISSUE TITLE
The tool does't work

### ISSUE THREAD

**Issue by olafchou** [ichord/sketch-divine-proportions#5]
Sketch Divine Proportions  does't work

**Comment by ichord** [comment]
which version?

**Comment by olafchou** [comment]
the newest version
            On 11/25/2016 16:01, Harold.Luo wrote:which version?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ichord/sketch-divine-proportions","title":"ichord/sketch-divine-proportions","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ichord/sketch-divine-proportions"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ichord in #5: which version?"}],"action":{"name":"View Issue","url":"https://github.com/ichord/sketch-divine-proportions/issues/5#issuecomment-262900245"}}}

**Comment by henryboldi** [comment]
Same issue here

**Comment by ophirsweiry** [comment]
Same issue
