### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [ichord/sketch-divine-proportions#6]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by ichord** [comment]
@bomberstudios please check your email inbox. I sent an email for getting help to update the plugin.

**Comment by jianggugu** [comment]
45.1版本只能画 Rectangle，其他的操作均无反应...

**Comment by ichord** [comment]
@jianggugu The demo script showed below is not working too, I asked for help, but no response yet.

```ruby
 var sketch = context.api()
  var document = sketch.selectedDocument
  var page = document.selectedPage

var layer = page.newShape({with: 100, height: 100})
```
